### ISSUE TITLE
2019.02.23 (토)

### ISSUE THREAD

**Issue by AlwaysAwake** [gogogo191/becomeadeveloper#3]
## 오늘 함께 볼 내용
* https://developer.mozilla.org/ko/docs/Learn/Server-side/First_steps 과 연계된 글들
* codecademy.com 진행 상황 점검
* javascript.info 어려웠던 챕터 함께 리뷰 & 점검
* 지난 강의 때 봤던 것들 체크

**Comment by gogogo191** [comment]
* javascript.info 2ch 복습하기
* 3ch 3.1부터 앞부분 복습 꼼꼼히하고, 뒷부분은 적당히 다시보기
* 4ch는 졸라 어려우니 4.1 꼼꼼히 공부하기
* codecademy는 6챕터까지 (until 6.Loops) 실습하기
